name: Docker Deployment Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch: #here task 3 of manulally triggering the workflow

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build new docker iamge
        run: |
          docker build -t final_select:latest . # coonect to local host to the other user

      - name: Trigger root deployment
        run: |
          #ssh-keyscan -H localhost >> ~/.ssh/known_hosts #update commands here 
          #ssh root@localhost << 'EOF'
           # echo "Stopping old container..."
            #docker stop my-python-app-container || true
            #docker rm my-python-app-container || true

            #echo "Starting new container with updated python script..."
            #docker run -d \
             # --name my-python-app-container \
              #--restart always \
              #-v /root/app/script.py:/app/script.py \
              #my-python-app:latest

            #echo "Pruning old unused images..."
            #docker image prune -f
          #EOF
